### ISSUE TITLE
Search w/ ++words

### ISSUE THREAD

**Issue by guilleasz** [Plataforma5/radix-trie#1]
Add method to search for more than 1 word. Could accept an array of words, make a search for each world and filter only the results that appear in all the searches.

**Comment by atralice** [comment]
Guille, 
I made a method called `findMany`. It receives an array of words. Its performs `findData` for each word and returns the intersection of those results.

I added and Id to each data field, so it would be easier to compute the intersection of results.

**Comment by guilleasz** [comment]
Great! I'm closing this issue
