### ISSUE TITLE
[Question] Performance Analysis

### ISSUE THREAD

**Issue by grandsong** [Plataforma5/radix-trie#5]
Could you do some performance analysis like what was done in [JavaScript Trie Performance Analysis](https://johnresig.com/blog/javascript-trie-performance-analysis/)?

In that article, it seems that hash beats trie. I guess the native hash lookup is optimized by js engine. What about in nowadays browsers (I like Chrome) or Node.js?

Is your lib really preferable over the native hash? If so, how much better in terms of data size, build speed, find speed, memory, etc?

**Comment by atralice** [comment]
Hi!
I think you should't compare this library against native hash over performance. You should compare them based on features, or what can you do with it.

In terms of speed  and space hash surely beats the trie. But, our main usage of this trie structure is to be able to find words by partials (this would still be faster in hash, but using a lot space) and also be able to perform auto completion of words.

So, if you want to look up whole words on a dictionary, go for the hash and don't use radix-trie.
But, if you need to look up partials words and get auto completion as you type, then use our library!

Hope you find this helpful.
Cheers.

**Comment by grandsong** [comment]
Thanks for your answer.
Maybe you could mention this in the readme (and in NPM, too).
Some people like me may learn Trie from articles about traditional (say, for C) algorithms, which usually take "performance over hash" as the first reason for using Trie.

**Comment by atralice** [comment]
> Some people like me may learn Trie from articles about traditional (say, for C) algorithms, which usually take "performance over hash" as the first reason for using Trie.

Totally agree on this.

> Maybe you could mention this in the readme (and in NPM, too).

Will do!

Thanks a lot!
